config/routes.rb
Rails.application.routes.draw do
  root "scenario#top"
    
  get 'search'     => 'scenario#search'
  get 'faker'      => 'scenario#faker'
  get 'screate'    => 'screate#top'
  post 'screate'    => 'screate#top'
  post 'screate_preview' => 'screate#preview'
  get 'texshare'    => 'texshare#top'
  get 'fake'       => 'scenario#fake'
  get 'fake_page/:url'  => 'scenario#fake_page' ,constraints: { url: /[^\/]+/ }
  post 'texshare/upload' => 'texshare#upload'
  get 'page/:url'       => 'texshare#page' ,constraints: { url: /[^\/]+/ }

end

app/controllers/scenario_controller.rb
require 'open-uri'
require 'hpricot'
require 'kconv'

JERICHO_URL ="http://jerichof.web.fc2.com/scenari0/"
NISHITETU_URL = "http://jerichof.web.fc2.com/w/memo/"
LAVINA_URL = "http://jerichof.web.fc2.com/scenari0/la_viena/"

class ScenarioController < ApplicationController
  # Basic認証フィルタを対象アクションに指定
  http_basic_authenticate_with :name => 'admin', :password => 'nyanyanya', :only => :top
  http_basic_authenticate_with :name => 'admin', :password => 'nyanyanya', :only => :search
  def top
  end

  def search
    @list = Hash.new()
    @scenario_num = []
    @scenario_list = params[:scenario_list]
    @num = params["num"].to_i
    @men = params["men"].to_i
    @women = params["women"].to_i
    @check = params[:check]
    @unchecked = params[:unchecked]
    @output_num = params[:output_num]
    @keyword = params[:keyword]
    case @scenario_list
    when "jericho941"
      jericho_scenario_search(JERICHO_URL+"top1897347f.htm")
    when "nishitetu"
      nishi_lavina_search(NISHITETU_URL + "itiran_all.htm")
    when "lavina"
      nishi_lavina_search(LAVINA_URL+"all.htm")
    when "news"
      jericho_scenario_search(JERICHO_URL+"news/top.htm")
    else
      scenario_put(JERICHO_URL+"top1897347f.htm")
    end
  end

  def faker
  end

  def fake_page
    url = params[:url]
    Dir::foreach('public/html') {|f|
      if f == "." || f == ".."
        next
      end
      if File.mtime("public/html/#{f}") < Time.now - 36000 * 3 
        File.unlink("public/html/#{f}")
      end
    }
    if File.exist?("public/html/#{url}")
      @html = File.read("public/html/#{url}").toutf8
    else
      redirect_to "/404.html"
    end
  end

  def fake
    url = params[:file_url]
    if url.blank?
      flash[:warning] = "URLを入力してください"
      redirect_to action:"faker"
    else
      fake_url = url.split("/").pop
      rand_name = html_edit(url)

      if rand_name 
        redirect_to "/fake_page/#{rand_name}-#{fake_url}"
      else
        redirect_to "/404.html"
      end
    end
  end

  #シナリオ検索
  def jericho_scenario_search(page_url)

    if @men != 0 || @women != 0 || @num != 0
      flg = false
      cnt = 0
      writer = ""

      split_url = page_url.gsub(/#{JERICHO_URL}/,"")
      doc = Hpricot(open(page_url).read)
      case @scenario_list
      when "jericho941"
        contents = doc.to_html.gsub!(/(\w|\.)\n/, '\1')
        contents.gsub!(/href=\"(.*)\"/, "href=\"#{JERICHO_URL}" + '\1' + "\"")
      when "news"
        contents = doc.to_html
        contents = contents.toutf8
        contents.gsub!(/href=\"(.*)\"/, "href=\"#{JERICHO_URL.scrub}news/" + '\1' + "\"")
      end

      if @check == "true"
        pattern = member_pattern(@men, @women, @num)
      end

      contents.lines{|line| 
        if line.toutf8 =~ /.*岡崎二郎.*/ && flg == false || line.toutf8 =~ /HR/i && flg == false
          flg = true
        elsif flg == false
          next
        end
        if line.toutf8 =~ /この台本はヤフー/
          break
        end

        if /<p>.+<\/p>/ =~ line.toutf8
          cnt = cnt + 1
          @scenario_num << cnt
          writer = line.toutf8
          @list[cnt] =[writer, line.toutf8]
          next
        end
        if /\((#{@men}|#{zenhan(@men)})-(#{@women}|#{zenhan(@women)})-(#{@num}|#{zenhan(@num_zen)}")/ =~ line.toutf8 
          if unchecked_check(line.toutf8)
            cnt = cnt + 1
            @scenario_num << cnt
            @list[cnt] =[writer, "<img src='/image/point017_02.gif'>#{line.toutf8.gsub(/\(\d.*\)/, " ")}" , scenario_retio(line.toutf8), member_sum(line.toutf8)]
          end
          next
        end

        if @check == "true"
          #合計人で検索
          if @men == 0 && @women == 0
            if /\((\d*|[０-９]*)-(\d*|[０-９]*)-(\d*|[０-９]*)-(#{@num}|#{zenhan(@num)})\)/ =~ line.toutf8 
              if unchecked_check(line.toutf8)
                @list[cnt] =[writer, "<img src='/image/point018_04.gif'>#{line.toutf8.gsub(/\(\d.*\)/, " ")}" , scenario_retio(line.toutf8), member_sum(line.toutf8)]
              end
            end

            #融通をきかせた比率
          else
            pattern.each{|p|
              if /\(#{(p["men" ])}-#{(p["women"])}-#{(p["num"])}/ =~ line.toutf8 
                if unchecked_check(line.toutf8)
                  cnt = cnt + 1
                  @scenario_num << cnt
                  @list[cnt] =[writer, "<img src='/image/point018_04.gif'>#{line.toutf8.gsub(/\(\d.*\)/, " ")}" , scenario_retio(line.toutf8), member_sum(line.toutf8)]
                end
                break
              end
            }
          end
        end
      }

    else
      scenario_put(page_url)
    end

  end#jericho_scenario_search

  #西鉄,ラヴィーナシナリオ検索
  def nishi_lavina_search(page_url)

    cnt = 0

    if @check == "true"
      pattern = member_pattern(@men, @women, @num)
    end

    case @scenario_list
    when "nishitetu"
      @base_url = NISHITETU_URL
    when "lavina"
      @base_url = LAVINA_URL
    end

    doc = Hpricot(open(page_url).read)
    contents = (doc/:"table/tr") 
    contents.each{|content| 
      line = (content/:"td/p")
      if line[0] == nil
        next
      end
      if html_utf8(line[1]) == "ON-AIR" || html_utf8(line[1]) == "O.A.日"
        next
      else
        if @men != 0 || @women != 0 || @num != 0
          if html_utf8(line[4]).to_i == @men && html_utf8(line[5]).to_i == @women && html_utf8(line[6]).to_i == @num
            if unchecked_check(line)
              cnt = cnt + 1
              @scenario_num << cnt
              @list[cnt] = line
            end
            next
          end

          if @check == "true"
            #合計人数で検索
            if @men == 0 && @women == 0
              if @num == html_utf8(line[7]).to_i
                if unchecked_check(line)
                  cnt = cnt + 1
                  @scenario_num << cnt
                  @list[cnt] = line
                end
              end

              #融通をきかせた比率
            else
              if @men + @women + @num == html_utf8(line[7]).to_i
                pattern.each{|p|
                  if html_utf8(line[4]).to_i == p["men"] && html_utf8(line[5]).to_i == p["women"] && html_utf8(line[6]).to_i == p["num"]
                    if unchecked_check(line)
                      cnt = cnt + 1
                      @scenario_num << cnt
                      @list[cnt] = line
                    end
                    break
                  end
                }
              end
            end
          end
        else
          if unchecked_check(line)
            cnt = cnt + 1
            @scenario_num << cnt
            @list[cnt] = line
          end
        end
      end
    }
  end#nishitetu_scenario_search()

  #融通を聞かせた時のパターン
  def member_pattern(men, women, num)

    pattern = []
    pattern << {
      "men" => men,
      "women" => women,
      "num" => num
      } 

    (1..num).each{|i|
      pattern << { 
        "men" => men + i,
        "women" => women,
        "num" => num - i
      } 

      pattern << { 
        "men" => men,
        "women" => women + i,
        "num" => num - i
      } 
    }

    num2 = num
    m_men = men + num
    m_women = women
    w_men = men
    w_women = women + num

    while(num2 > 0)
      if m_men > men 
        m_men = m_men - 1
        m_women = m_women + 1

        if pattern_check(pattern, m_men, m_women, num - num2)
          pattern << { 
            "men" => m_men,
            "women" => m_women,
            "num" => num - num2
          } 
        end
      end
      if w_women > women
        w_men = w_men + 1
        w_women = w_women - 1

        if pattern_check(pattern, w_men, w_women, num - num2)
          pattern << { 
            "men" => w_men,
            "women" => w_women,
            "num" => num - num2
          }
        end
      end
      if w_women <= women && m_men <= men
        num2 = num2 - 1
        m_men = men + num2
        m_women = women
        w_men = men
        w_women = women + num2
      end
    end

    (1..men).each{|m|
      if pattern_check(pattern, w_men, w_women, num - num2)
        pattern << { 
          "men" => men - m,
          "women" => women,
          "num" => num + m
        } 
      end
      (1..women).each{|w|
        if pattern_check(pattern, w_men, w_women, num - num2)
          pattern << { 
            "men" => men - m,
            "women" => women - w,
            "num" => num + m + w 
          } 
        end
      }
    }
    (1..women).each{|w|
      if pattern_check(pattern, w_men, w_women, num - num2)
          pattern << { 
            "men" => men,
            "women" => women - w,
            "num" => num + w
          } 
      end
    }

    return(pattern)

  end#member_pattern()

  def pattern_check(pattern, men, women, num)
    pattern.each{|p|
      if p["men"] == men && p["women"] == women && p["num"] == num
        return true
      end
    }
    return false 
  end

  def scenario_retio(title)

    /\((\d*|[０-９]*)-(\d*|[０-９]*)-(\d*|[０-９]*)/ =~ title
    retio = "<font color=\"blue\">#{$1.to_s}</font>:<font color=\"#DF01D7\">#{$2.to_s}</font>:#{$3.to_s}"
    return(retio)

  end

  def member_sum(title)
    /\((\d*|[０-９]*)-(\d*|[０-９]*)-(\d*|[０-９]*)/ =~ title
    sum = $1.to_i + $2.to_i + $3.to_i
    return(sum)

  end

  def unchecked_check(title)
    case @unchecked
    when "checked"
      if title =~ /^・/
        return false
      end
    when "unchecked"
      unless title =~ /^・/
        return false
      end
    end
      return true
  end

  def zenhan(str)
    return(str.to_s.tr!("0-9", "０-９"))
  end

  #全シナリオ出力
  def scenario_put(page_url)
    flg = false
    cnt = 0
    writer = ""

    split_url = page_url.gsub(/#{JERICHO_URL}/,"")
    doc = Hpricot(open(page_url).read)
    if @scenario_list == "news"
      contents = doc.to_html
      contents = contents.toutf8
      contents.gsub!(/href=\"(.*)\"/, "href=\"#{JERICHO_URL.scrub}news/" + '\1' + "\"")
    else
      contents = doc.to_html.gsub!(/(\w|\.)\n/, '\1')

app/helpers/scenario_helper.rb
module ScenarioHelper
require 'kconv'
  def html_utf8(elem)
    return(elem.inner_html.toutf8)
  end#html_utf8
end

app/views/scenario/_jericho941.html.erb
<%= stylesheet_link_tag "scenario/jericho941", :media => "all" %>
<%= stylesheet_link_tag "scenario/main", :media => "all" %>
<script>
var nisilove = false;
</script>

<div id="main-contents">
  全<%=@scenario_num.length%>件
  <table id="item_table" class="sicenairo_list table-striped table-bordered">
    <thead>
      <tr class="list-label">
        <td class='fake_top'>偽</td>
        <td class='scenario_top'>台本</td>
        <td class="writer_top">作者・作品</td>
        <td class="retio_top">比率</td>
        <td class="sum_top">計</td>
      </tr>
    </thead>
    <tbody>
    <%scenario_cnt = 0

    if @output_num.present?
      @scenario_num = @scenario_num.sort_by{rand}
    end
    @scenario_num.each{|scenario_n|
      if @keyword.blank? || /#{@keyword}/i =~ @list[scenario_n][0] || /#{@keyword}/i =~ @list[scenario_n][1]
        @list[scenario_n][0].gsub!(/<p>|<\/p>/, '')
        if /<p>.+<\/p>/ =~ @list[scenario_n][1] 
          next
        end
        if @output_num.blank? || @output_num.present? && @output_num.to_i > scenario_cnt
          scenario_cnt = scenario_cnt + 1
          %><tr class="list">
            <%	@list[scenario_n][1] =~ /href=\"(.*)\"\s.*\"/
            file_url = $1%>
          <td class="fake"><%= link_to "Fake",fake_path(file_url: file_url), target:'_blank'%></td>
            <td class="title"><%=raw @list[scenario_n][1]%></td>
            <td class="writer"><%=@list[scenario_n][0]%></td>
            <td class="retio"><%=raw @list[scenario_n][2]%></td>
            <td class="sum"><%=@list[scenario_n][3]%></td>
          </tr><%
        else
          break
          end
      end
    }
  %>
  </tbody>
  </table>
</div>

app/views/scenario/_lavina.html.erb
<%= stylesheet_link_tag "scenario/nishi_love", :media => "all" %>
<%= stylesheet_link_tag "scenario/main", :media => "all" %>
<script>
var nisilove = true;
</script>
<div id="main-contents">
<table id="item_table" class="sicenairo_list table-striped table-bordered">
  <% scenario_cnt = 0 %>
  <thead>
    <tr class="list-label">
      <td class='number list-label'>No.</td>
      <td class='o_a list-label'>O.A.日</td>
      <td class='fake list-label'>偽</td>
      <td class='title_la list-label'>タイトル</td>
      <td class='writer list-label'>作者</td>
      <td class='men list-label'>比率</td>
      <td class='sum list-label'>計</td>
      <td class='other_la list-label'>備考1</td>
      <td class='other_la list-label'>備考2</td>
      <td class='other_la list-label'>備考3</td>
    </tr>
  </thead>
  <tbody>
  <% if @random_check == "true"
       @scenario_num = @scenario_num.sort_by{rand}
  end
  @scenario_num.each{|random_s|
    if @keyword.blank? || /#{@keyword}/i =~ html_utf8(@list[random_s][2]) || /#{@keyword}/i =~ html_utf8(@list[random_s][3])
      if @random_check.blank? || @random_check == "true" && @output_num.to_i > scenario_cnt
        html_utf8(@list[random_s][2]) =~ /href=\"(.*)\"\s.*\"/
        file_url = $1
        if file_url == nil
          next
        else
          scenario_cnt = scenario_cnt + 1
          %><tr class="list">
            <td class='number'><%=html_utf8(@list[random_s][0])%></td>
            <td class='o_a'><%=raw html_utf8(@list[random_s][1])%></td>
            <td class="fake"><%= link_to "Fake",fake_path(file_url: file_url), target:'_blank'%></td>
            <td class='title_la'><%=raw html_utf8(@list[random_s][2]).gsub(/href=\"(.*)\"/, "href='" + file_url + "' target=\'_blank\'")%></td>
            <td class='writer'><%=html_utf8(@list[random_s][3])%></td>
            <td class='men'><font color="blue"><%=html_utf8(@list[random_s][4])%></font>:<font color="#DF01D7"><%=html_utf8(@list[random_s][5])%></font>:<%=html_utf8(@list[random_s][6])%><br>
              (<%=html_utf8(@list[random_s][8]).to_i%>:<%=html_utf8(@list[random_s][9]).to_i%>:<%=html_utf8(@list[random_s][10]).to_i%>)
            </td>
            <td class='sum'><%=html_utf8(@list[random_s][7])%></td>
            <td class='other_la'><%=raw html_utf8(@list[random_s][11])%></td>
            <td class='other_la'><%=raw html_utf8(@list[random_s][12])%></td>
            <%if @list[random_s][13] != nil
            %><td class='other_la'><%=raw html_utf8(@list[random_s][13])%></td>
          <%end%>
          </tr>
        <%end
      else
        break
      end
    end
  }

  %></tbody>
</table>
全<%=scenario_cnt%>件

</div>

app/views/scenario/_nishitetu.html.erb
<%= stylesheet_link_tag "scenario/nishi_love", :media => "all" %>
<%= stylesheet_link_tag "scenario/main", :media => "all" %>
<script>
var nisilove = true;
</script>
<div id="main-contents">
<table id="item_table" class="sicenairo_list table-striped table-bordered">
  <thead>
    <tr class="list-label">
      <td class='number list-label'>No.</td>
      <td class='number list-label'>ON-AIR</td>
      <td class='fake list-label'>偽</td>
      <td class='title list-label'>タイトル</td>
      <td class='writer list-label'>作者</td>
      <td class='men list-label'>比率</td>
      <td class='sum list-label'>計</td>
      <td class='other1 list-label'>備考1</td>
      <td class='other2 list-label'>備考2</td>
    </tr>
  </thead>
  <tbody>
  <% scenario_cnt = 0
  if @random_check == "true"
    @scenario_num = @scenario_num.sort_by{rand}
  end
  @scenario_num.each{|random_s|
    if @keyword.blank? || /#{@keyword}/i =~ html_utf8(@list[random_s][2]) || /#{@keyword}/i =~ html_utf8(@list[random_s][3])
      if @random_check.blank? || @random_check == "true" && @output_num.to_i > scenario_cnt
        scenario_cnt = scenario_cnt + 1
        html_utf8(@list[random_s][2]) =~ /href=\"(.*)\"\s.*\"/
        file_url = $1%>
      <tr class="list">
          <td class='number'><%=html_utf8(@list[random_s][0])%></td>
          <td class='number'><%=html_utf8(@list[random_s][1])%></td>
          <td class="fake"><%= link_to "Fake",fake_path(file_url: @base_url+file_url), target:'_blank'%></td>
          <td class='title'><%=raw html_utf8(@list[random_s][2]).gsub(/href=\"(.*)\"/, "href='" + @base_url + file_url + "' target=\'_blank\'")%></td>
          <td class='writer'><%=html_utf8(@list[random_s][3])%></td>
          <td class='men'><font color="blue"><%=html_utf8(@list[random_s][4])%></font>:<font color="#DF01D7"><%=html_utf8(@list[random_s][5])%></font>:<%=html_utf8(@list[random_s][6])%><br>
            (<%=html_utf8(@list[random_s][8]).to_i%>:<%=html_utf8(@list[random_s][9]).to_i%>:<%=html_utf8(@list[random_s][10]).to_i%>)
          </td>
          <td class='sum'><%=html_utf8(@list[random_s][7])%></td>
          <td class='other1'><%=html_utf8(@list[random_s][11])%></td>
          <td class='other1'><%=raw html_utf8(@list[random_s][12])%></td>
        </tr><%
      else
        break
        end
    end
  }

  %>
  </tbody>
</table>
全<%=scenario_cnt%>件
</div>

app/views/scenario/fake_html.html.erb
<%= raw @html %>

app/views/scenario/faker.html.erb
<style>
body{
  background-color: #F5F5F5;
}
#main-contents{
  margin-right: auto;
  margin-left : auto;
  width:700px;
  border: 1px solid #D3D3D3;
  background-color: #FFF;
  border-radius: 5px;
  padding:10px;
  margin-top:10px;
}
</style>
<% provide(:title, "URL Faker") %>
<div id="main-contents">
  <h2>URL Faker</h2><br>
  ページを偽装して別のURLで表示。<br>
  作成から３時間でページは消滅。<br>
  <br>
  <br>
  <form action='fake' method='GET' target="_blank">
    Fake URL<br><input type='text' class="form-control" name='file_url' size="120"><br>
    <input type='submit' class="btn btn-success" value="偽装する">
  </form>
  <hr>
  <br>
  <% unless @fake_url.blank? %>
    <b><a href='./url/<%=rand_name%>-<%=@fake_url%>' target="blank">Fake page</a><br>
    URL：<input type="text" id="txt2" size="120"value="http://kazu.media-shelf.net/Faker/url/<%=rand_name%>-<%=@fake_url%>"><br>
    <div id="swf2" class="btn">[copy]</div>
  </b><br>
  <br>
  元URL : <a href='<%=@cgi["url"]%>' target="blank"><%=@cgi["url"]%></a><br><hr>
<% end %>

  <a href="javascript:(function(){ window.open('<%= root_url %>fake?file_url='+(location.href).replace('l50', '')); })();"><strong>Bookmarklet</strong></a>
  <br>
  <font size="2">↑のリンクをブックマーク保存し、フェイクを作成したいページを開いた状態で、<br>登録したブックマークをクリックするとそのページのフェイクを作成可能。<br>
  <br>
</div>

app/views/scenario/ruby_text.html.erb
<%= @my_data %>

app/views/scenario/search.html.erb
<html lang="ja">
  <head>
    <% provide(:title, "台本検索") %>
  </head>
  <body>
  <% if @scenario_list.blank? || @scenario_list == "news"%>
    <%= render "jericho941" %>
  <% else %>
    <%= render @scenario_list %>
  <% end %>
  </body>
</html>

app/views/scenario/top.html.erb
<style>
body{
  background-color: #F5F5F5;
}
#main-contents{
  margin-right: auto;
  margin-left : auto;
  width:700px;
  border: 1px solid #D3D3D3;
  background-color: #FFF;
  border-radius: 5px;
  padding:10px;
  margin-top:10px;
}
.select-box-1{
  width:150px;
}
.select-box-2{
  width:95px;
}
.keyword{
  width:250px;
}
.sex{
  font-size:18px;
  margin-right:5px;
  margin-left:5px;
}
h4{
  border-left: 3px solid #228B22;
  padding-left:2px;
}
</style>

<% provide(:title, "台本検索") %>
<div id="main-contents">
  <h2>台本検索</h2>
  <form name="form" method="POST" action="./search" target="_blankk">
    <input type="hidden" name="process" value="all">
  </form>
  <br>
  <form name= "search" action='./search' method='GET'>
    <input type='radio' name='scenario_list' value='jericho941' checked="checked">jericho941<br>
    <input type='radio' name='scenario_list' value='nishitetu'>西鉄台本<br>
    <input type='radio' name='scenario_list' value='lavina'>ラヴィーナ<br>
    <input type='radio' name='scenario_list' value='news'>NEWS<br>
    <br>
    <select name='unchecked' class="form-control select-box-1">
      <option value='all'>全て</option>
      <option value='checked'>チェック済</option>
      <option value='unchecked'>未チェック</option>
    </select><br>

    <div class="form-inline">
      <span class="sex">男</span><select name='men' class="form-control">
        <%for cnt in 0..20 do%><option value='<%=cnt.to_s%>'><%=cnt.to_s%></option>
        <%end
        %></select> 
      <span class="sex">女</span><select name='women' class="form-control">
        <%for cnt in 0..20 do%><option value='<%=cnt.to_s%>'><%=cnt.to_s%></option>
        <%end
        %></select>
      <span class="sex">不問</span><select name='num' class="form-control">
        <%for cnt in 0..20 do%><option value='<%=cnt.to_s%>'><%=cnt.to_s%></option>
        <%end
        %></select>
      <input type="checkbox" name="check" value="true">融通を利かす<br>
    </div>
    <br>
    ランダム出力
    <select name='output_num' class="form-control select-box-2">
      <option value=''>無効</option>
      <option value='5'>5件</option>
      <% (1..10).each{|c| %>
        <option value='<%=c*10%>'><%=c*10%>件</option>
      <% } %>
    </select>
    <br>
    <br>
    キーワード検索<br>
    <input type="text" name="keyword" class="form-control keyword"><br>
    <input type='hidden' name='process' value='search'><br><br>
    <input type='submit' class="btn btn-success" value="検索">
  </form>
  <br>
  <br>
  <h4>その他のツール</h4>
  <strong><%= link_to "URL Faker", faker_path %></strong><br>
  ページを別のURLで表示（３時間後に消滅）。
  <br>
  <br>
  <strong><%= link_to "台本作成ツール", "/screate" %></strong><br>
  エクセルの表をHTMLのテーブルに変換。
  <br>
  <br>
  <strong><%= link_to "テキストファイル共有", "/texshare" %></strong><br>
  テキストファイルを共有。
  <br>
  <br>
</div>